<?php
/**
 * SSO Handler for Control Panel Login
 *
 * Handles single sign-on tokens generated by the control panel to authenticate users.
 *
 * @package ControlPanelConnector
 * @since 1.5.0
 * @author PanelAlpha
 */

declare(strict_types=1);

namespace ControlPanelConnector;

use ControlPanelConnector\Repository\FeedRepository;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * SSO Handler class
 */
class SSO {

    /**
     * Option key used to mark that the one-time onboarding redirect has already been performed
     * for this WordPress installation.
     */
    private const ONBOARDING_REDIRECT_DONE_OPTION = 'controlpanel_sso_onboarding_redirect_done';

    /**
     * Feed repository instance
     */
    private FeedRepository $feedRepository;

    /**
     * Constructor
     *
     * @param FeedRepository $feedRepository Feed repository instance
     */
    public function __construct( FeedRepository $feedRepository ) {
        $this->feedRepository = $feedRepository;
    }

    /**
     * Register all SSO hooks and CLI commands
     */
    public function register(): void {
        add_action( 'init', array( $this, 'handleSsoLogin' ) );
    }

    /**
     * Handle SSO login from control panel
     *
     * Processes SSO tokens, validates expiration, and logs in the user if valid.
     *
     * @return void
     */
    public function handleSsoLogin(): void {
        if ( empty( $_REQUEST['controlpanel_sso'] ) || ! is_string( $_REQUEST['controlpanel_sso'] ) ) {
            return;
        }

        $token = sanitize_text_field( wp_unslash( $_REQUEST['controlpanel_sso'] ) );

        $users = get_users(
            array(
                'meta_key'   => 'controlpanel_sso',
                'meta_value' => sha1( $token ),
                'number'     => 1,
                'fields'     => 'id',
            )
        );

        if ( empty( $users ) ) {
            return;
        }

        $userId = (int) $users[0];

        [$expires]   = explode( '_', $token );
        $expiresTime = (int) $expires;

        // Check expiration BEFORE deleting from database to prevent race conditions
        if ( time() > $expiresTime ) {
            delete_user_meta( $userId, 'controlpanel_sso' );
            return;
        }

        // Token is valid, delete it and log in the user
        delete_user_meta( $userId, 'controlpanel_sso' );

        wp_set_current_user( $userId );
        wp_set_auth_cookie( $userId );

        $redirectUrl = user_admin_url();

        $onboardingAlreadyDone = (bool) get_option( self::ONBOARDING_REDIRECT_DONE_OPTION, false );
        if ( ! $onboardingAlreadyDone ) {
            $redirectUrl = $this->applyOnboardingRedirect( $redirectUrl );
            update_option( self::ONBOARDING_REDIRECT_DONE_OPTION, 1, true );
        }

        wp_safe_redirect( $redirectUrl );
        exit;
    }

    /**
     * Applies Onboarding launch redirect query when onboarding is enabled in the feed.
     *
     * @param string $redirectUrl Base redirect URL.
     * @return string Updated redirect URL.
     */
    private function applyOnboardingRedirect( string $redirectUrl ): string {
        $feed              = $this->feedRepository->get();
        $onboardingOptions = is_array( $feed['onboarding'] ?? null ) ? $feed['onboarding'] : array();

        $onboardingEnabled = (bool) ( $onboardingOptions['enabled'] ?? false );
        if ( ! $onboardingEnabled ) {
            return $redirectUrl;
        }

        $launchQuery = $onboardingOptions['launch_query'] ?? '';
        if ( ! empty( $launchQuery ) ) {
            $redirectUrl = admin_url();
            return $redirectUrl . $launchQuery;
        }

        return $redirectUrl;
    }
}
